### ISSUE TITLE
TODO List for RAT usability

### ISSUE THREAD

**Issue by operatorequals** [operatorequals/covertutils#13]
These tasks are the least needed to be fixed/implemented for using this package in real assessments.

- [ ] Ability to Change Communication Passphrase at *Check-in*
- [ ] Implementation of a `MultiHandler` with single `recv()` for multiple `*Handler` objects
- [ ] Integration of `MultiHandler` with `covertpreter` shell
- [ ] Implementation of a `portfwd` command for *pivoting*
- [ ] Implementation of an `stdapi` extension for cross-platform commands (`ls`, `getuid`, etc - *meterpreter style*)

**Comment by ghost** [comment]
Hey @operatorequals, Is this project still being developed ? I started playing with it for the last week and seems like it has a huge potential. Thanks for all your hard work.

**Comment by operatorequals** [comment]
Hello!
This project is not that alive as you can see from the commit history. It reached a certain point that couldn't surpass because of architectural decisions that weren't working, as the requirements started changing a lot during development.

The idea truly has potential, as there is no Development-Friendly RAT out there (no docs, no [intuitive] APIs, etc), so one is really needed. Yet the idea has to be re-designed.

If you want to work with it, I can surely try to give you some insight on the things that you might want to prefer and avoid. I might even contribute too :)

**Comment by ghost** [comment]
@operatorequals Hey, thanks for quick reply and do apologize for my long one. I was wondering what would stop me from developing my own rat, what are the architectural decisions that were not working ? I have been following your blog about this project and you have a nice way of explaining difficult subjects in a very accessible way. Your readthedocs documentation is great; very detailed that's why I started playing with it. Seems like you had paved the way to creating a first backdoor from scratch with minimal python skills (which I am still learning).

I wont be able to take it further as my python Kung Fu is not there yet but I am still sticking to my project for now. 

Question I was wondering how I can load modules (such as covertutils.payloads.windows.shellcode) on start with tcp or http handler ? I tried overriding extendable shell bit, but it will only load the base without adding the correct OS shellcode ?
Is the reverse UDP, ICMP and DNS only options on Linux as of now or can they work with Windows too ?
PS. I understand you are busy, so I do not need lengthy answers, just pointers in the right direction.
